name: Net Presence CI
on:
  push:
    branches:
      - '*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go ${{ matrix.goVer }}
      uses: actions/setup-go@v3
      with:
        go-version: '1.21'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Make release notes
      if: contains(github.ref, 'tags')
      run: |
        echo 'RELEASE_NOTES<<EOF' >> $GITHUB_ENV
        TAG=$GITHUB_REF_NAME hack/make-release-notes.sh >> $GITHUB_ENV
        echo 'EOF' >> $GITHUB_ENV

    - name: Create a new release
      if: contains(github.ref, 'tags')
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ github.ref_name }}
        files: out/krew*
        body: ${{ env.RELEASE_NOTES }}
        fail_on_unmatched_files: true